name: follow_the_leader
description: Widgets that follow other widgets.
homepage: https://github.com/Flutter-Bounty-Hunters/follow_the_leader
repository: https://github.com/Flutter-Bounty-Hunters/follow_the_leader

version: 0.0.5

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  logging: ^1.0.1
  super_keyboard: ^0.2.2
  vector_math: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  flutter_test_goldens: 0.0.7

flutter:

