name: Run analysis and tests for pull requests
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the PR branch
      - uses: actions/checkout@v3

      # Setup Flutter environment
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      # Download all the packages that the app uses
      - run: flutter pub get

      # Static analysis
      - run: flutter analyze

      # Run all tests
      - run: flutter test

  test_goldens:
    runs-on: macos-latest
    steps:
      # Checkout the PR branch
      - uses: actions/checkout@v3

      # Setup Flutter environment
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64

      # Download all the packages that the app uses
      - run: flutter pub get

      # Static analysis
      - run: flutter analyze

      # Run all tests
      - run: flutter test test_goldens

      # Archive golden failures
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: golden-failures
          path: "**/failures/**/*.png"
